package Game.Menu;

public enum State {
    MAIN_MENU, SNAKE_MENU, TETRIS_MENU, CARO_MENU, SNAKE_GAME,SNAKE_GAME_OVER,
    TETRIS_GAME,TETRIS_GAME_OVER, CARO_GAME, CARO_END_GAME, PONG_MENU, PONG_GAME,PONG_GAME_OVER,
}
